title: 廖琴文｜个人主页
page-top-title: 廖琴文
top-section-bg-text: 廖琴文｜个人主页
home-subtitle: 廖琴文
copyright-text: '© Qinwen Liao 2026. 保留所有权利。'
nav-home: 首页
nav-education: 教育背景
nav-experience: 研究实习
nav-awards: 荣誉奖项
nav-publications: 学术发表
nav-skills: 兴趣爱好
education-label: 教育背景
experience-label: 研究实习
awards-label: 荣誉奖项
publications-label: 学术发表
skills-label: 兴趣爱好
menu-label: 菜单
license-link: 许可证
language-label: 语言
navigation-label: 展开或收起导航
photo-label: 廖琴文的照片
